### PR TITLE
Report trailing addresses scanned

### PR DESCRIPTION
**Pull request by qha**
This pull request needs a thorough review as it's been quite a while since i worked with C structs, unions and memory management.

Also it's not clear to me why the if statement in the specfile would specify 34 for python3_pkgversion only on el6 so i may have misunderstood something there but i couldn't install the packages without that change.

### CODE REVIEW

**Comment by qha** [comment]
I am working on a small change to send uninitialised addresses from haddrscan_detector the same way as haddrscan_aggregator does. You might want to hold of on reviewing/merging until i push that.

**Comment by qha** [comment]
Uninitialised addresses from haddrscan_detector are sent the same way as from haddrscan_aggregator in this version.

**Comment by qha** [comment]
Sorry, there seems to be a bug in the last push.

**Comment by qha** [comment]
Bug squashed.

**Comment by cejkato2** [comment]
When I see the changes, I think we should rework the concept of output format because UniRec does not support arrays right now and duplication of fields is not very sustainable approach.
We should think about rewriting the set of haddrscan modules (as we already did for vportscan) and use JSON output from the detector. Any comments? @vaclavbartos @qha

**Comment by vaclavbartos** [comment]
I agree, if there's a need to send multiple values of a key (like multiple DST_IPs in this case), it's better to use JSON output. Even in C it's usually not difficult to implement, it's just about filling values into a prepared JSON template (e.g. using snprintf and some loop for the array).

Side note: It would be great to add array support to UniRec, but that would be a lot of work (and probably difficult to do in a backward-compatible way).

**Comment by qha** [comment]
In principle i agree as i seem to remember that i have an email from @cejkato2 explaining how to produce email alerts from json records though i haven't had time to look into it yet.

I hope that this change can be coordinated with adding a resolver module for json records.

I would be very happy though if this pr could be merged in the mean time so that our haddrscan detection doesn't fail until i rebuild nemea-detectors on each release.

**Pull request merged**
